/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/membership/detail': RouteRecordInfo<'/admin/membership/detail', '/admin/membership/detail', Record<never, never>, Record<never, never>>,
    '/admin/membership/listing': RouteRecordInfo<'/admin/membership/listing', '/admin/membership/listing', Record<never, never>, Record<never, never>>,
    '/admin/payment/listing': RouteRecordInfo<'/admin/payment/listing', '/admin/payment/listing', Record<never, never>, Record<never, never>>,
    '/admin/registration/detail': RouteRecordInfo<'/admin/registration/detail', '/admin/registration/detail', Record<never, never>, Record<never, never>>,
    '/admin/registration/listing': RouteRecordInfo<'/admin/registration/listing', '/admin/registration/listing', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/registration/': RouteRecordInfo<'/registration/', '/registration', Record<never, never>, Record<never, never>>,
    '/registration/index2': RouteRecordInfo<'/registration/index2', '/registration/index2', Record<never, never>, Record<never, never>>,
  }
}
